sonar.projectKey=simple-node-docker-ci
sonar.projectName=Simple Node Docker CI
sonar.sources=app
sonar.host.url=http://host.docker.internal:9000
sonar.login=squ_331277bbabb11b97d1e4ee8393da7fb25b2b8d5d   # Use this only for local quick scan
